### ISSUE TITLE
Determine the order of `Bug`, `Enh`, `New` and `Chg` in change log

### ISSUE THREAD

**Issue by vjik** [yiisoft/docs#130]
Here: https://github.com/yiisoft/docs/blob/master/021-changelog-upgrade.md

**Comment by samdark** [comment]
Bug → Enh → Chg → New.

**Comment by vjik** [comment]
New
Chg
Enh
Bug

?

**Comment by samdark** [comment]
Yes. I've posted it in reverse order :)
