### ISSUE TITLE
Undefined class Controller

### ISSUE THREAD

**Issue by alexkart** [yiisoft/docs#25]
What is the fully qualified name of the class `Controller` in this example in https://github.com/yiisoft/docs/blob/master/guide/en/structure/middleware.md?
```php
$authorizedAction = new Controller(SiteController::class, 'auth', $container);
```

**Comment by razonyang** [comment]
I think it is `Yiisoft\Yii\Web\Middleware\ActionCaller`:

```php
$authorizedAction = new Yiisoft\Yii\Web\Middleware\ActionCaller(SiteController::class, 'auth', $container);
```

**Comment by alexkart** [comment]
@razonyang thanks
