### ISSUE TITLE
Typo in 'Saying Hello'

### ISSUE THREAD

**Issue by mbunyan** [yiisoft/docs#53]
"src/Controller/Echo.php"
should read
"src/Controller/EchoController.php"

Just a suggestion: Instead of 'Echo' use 'Hello' or 'Greeting', which would enable reader to easily create the 'Form' guide without rewriting the files from that example.

Otherwise, description works well for me

Mike B

**Comment by samdark** [comment]
Fixed the typo.

The name "echo" represents what controller does better. Also I've intentionally made form tutorial overwrite previous files. I still think that current version is OK.
