### ISSUE TITLE
What is the ideal way to work with modules in this new architecture?

### ISSUE THREAD

**Issue by j1myx** [yiisoft/docs#92]
https://www.yiiframework.com/doc/guide/2.0/en/structure-modules

**Comment by j1myx** [comment]
Thanks for your quick response @samdark. I was referring to this fabulous feature: https://www.yiiframework.com/doc/guide/2.0/en/structure-modules

**Comment by samdark** [comment]
@j1myx which features exactly?

**Comment by j1myx** [comment]
I mean the complete decoupling that a module had from the entire web application. Since having the views, controllers, etc. separate from the rest of the application, it made the project structure more neat. This order had many advantages considering that yii2 used it a lot in single component projects, for example, the joint work of n programmers.

Apparently this architecture was born to cover microservices, leaving aside how well the previous architecture worked to work with monorepos.

**Comment by samdark** [comment]
Yii 3 allows all that without having to create modules. See how classes are grouped together by use-case: https://github.com/yiisoft/yii-demo/tree/master/src/User. Later we may come for extra functionality to make it even more convenient.

**Comment by j1myx** [comment]
Thanks for the info @samdark . I really appreciate the enormous effort
doing to improve this great framework.
